#[derive(Clone, Copy, PartialEq)]
pub enum Tile {
    EMPTY,
    GROUND
}

pub type Map = [[Tile; 30]; 30];

pub fn read_map() -> Map {
    //TODO: read map from a file
    LEVEL_0
}

const LEVEL_0: Map = [
    //turn your head to the right to read this
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
    [Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::GROUND, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY, Tile::EMPTY],
];